#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-keyvault-administration
Version  : 4.0.0b2
Release  : 2
URL      : https://files.pythonhosted.org/packages/93/14/ee5ec47f59d8a2764f5f3d5e0065b5fcb82ec203e97f0ebae79c67ebf483/azure-keyvault-administration-4.0.0b2.zip
Source0  : https://files.pythonhosted.org/packages/93/14/ee5ec47f59d8a2764f5f3d5e0065b5fcb82ec203e97f0ebae79c67ebf483/azure-keyvault-administration-4.0.0b2.zip
Summary  : Microsoft Azure Key Vault Administration Client Library for Python
Group    : Development/Tools
License  : MIT
Requires: azure-keyvault-administration-python = %{version}-%{release}
Requires: azure-keyvault-administration-python3 = %{version}-%{release}
Requires: azure-common~
Requires: azure-core
Requires: msrest
BuildRequires : azure-common~
BuildRequires : azure-core
BuildRequires : buildreq-distutils3
BuildRequires : msrest

%description
# Azure KeyVault Administration client library for Python
Azure Key Vault helps solve the following problems:
- Vault administration (this library) - role-based access control (RBAC), and vault-level backup and restore options
- Cryptographic key management ([azure-keyvault-keys](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-keys)) - create, store, and control
access to the keys used to encrypt your data
- Secrets management
([azure-keyvault-secrets](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-secrets)) -
securely store and control access to tokens, passwords, certificates, API keys,
and other secrets
- Certificate management
([azure-keyvault-certificates](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-certificates)) -
create, manage, and deploy public and private SSL/TLS certificates

%package python
Summary: python components for the azure-keyvault-administration package.
Group: Default
Requires: azure-keyvault-administration-python3 = %{version}-%{release}

%description python
python components for the azure-keyvault-administration package.


%package python3
Summary: python3 components for the azure-keyvault-administration package.
Group: Default
Requires: python3-core
Provides: pypi(azure_keyvault_administration)
Requires: pypi(azure_common)
Requires: pypi(azure_core)
Requires: pypi(msrest)

%description python3
python3 components for the azure-keyvault-administration package.


%prep
%setup -q -n azure-keyvault-administration-4.0.0b2
cd %{_builddir}/azure-keyvault-administration-4.0.0b2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607992252
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
